# Generated by Django 2.1.3 on 2019-06-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_commonfields_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jobs.CommonFields'),
            preserve_default=False,
        ),
    ]
