# Generated by Django 2.1.3 on 2019-06-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_education_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='country',
            new_name='common',
        ),
    ]
