# Generated by Django 2.1.3 on 2019-06-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190608_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='common',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='CommonFields',
        ),
    ]
